### ISSUE TITLE
INVALID_ARGUMENT error during decompression on GPU

### ISSUE THREAD

**Issue by duanzhiihao** [tensorflow/compression#147]
**Describe the bug**
Hi, when I run the following commands on a GPU-enabled machine:
```
python tfci.py compress ms2020-cc10-mse-1 kodim01.png kodim01.tfci
python tfci.py decompress kodim01.tfci kodim01.tfci.png
```
where `kodim01.png` is the first Kodak image,

it reports the following error during decompression (compression can be done without errors):
```
2022-07-12 13:59:03.957194: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:03.961945: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:03.962046: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0712 13:59:05.385311 139916280263488 saver.py:1634] Saver not created because there are no variables in the graph to restore
2022-07-12 13:59:06.171514: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-12 13:59:06.172373: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.172523: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.172622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.543771: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.543891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.543978: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-12 13:59:06.544051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22290 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
2022-07-12 13:59:13.076625: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8201
Traceback (most recent call last):
  File "/ssd0/projects/tfc-test/tfci.py", line 401, in <module>
    app.run(main, flags_parser=parse_args)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/ssd0/projects/tfc-test/tfci.py", line 389, in main
    decompress(args.input_file, args.output_file)
  File "/ssd0/projects/tfc-test/tfci.py", line 209, in decompress
    output_image, = receiver(*tensors)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 1602, in __call__
    return self._call_impl(args, kwargs)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/wrap_function.py", line 243, in _call_impl
    return super(WrappedFunction, self)._call_impl(
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 1620, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 1669, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 1860, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/function.py", line 497, in call
    outputs = execute.execute(
  File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert' defined at (most recent call last):
    File "/ssd0/projects/tfc-test/tfci.py", line 401, in <module>
      app.run(main, flags_parser=parse_args)
    File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/ssd0/projects/tfc-test/tfci.py", line 389, in main
      decompress(args.input_file, args.output_file)
    File "/ssd0/projects/tfc-test/tfci.py", line 201, in decompress
      receiver = instantiate_model_signature(packed.model, "receiver")
    File "/ssd0/projects/tfc-test/tfci.py", line 97, in instantiate_model_signature
      return wrapped_import.prune(inputs, outputs)
Node: 'channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert'
Detected at node 'channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert' defined at (most recent call last):
    File "/ssd0/projects/tfc-test/tfci.py", line 401, in <module>
      app.run(main, flags_parser=parse_args)
    File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 312, in run
      _run_main(main, args)
    File "/home/duanzh/miniconda3/envs/tf-compression/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
      sys.exit(main(argv))
    File "/ssd0/projects/tfc-test/tfci.py", line 389, in main
      decompress(args.input_file, args.output_file)
    File "/ssd0/projects/tfc-test/tfci.py", line 201, in decompress
      receiver = instantiate_model_signature(packed.model, "receiver")
    File "/ssd0/projects/tfc-test/tfci.py", line 97, in instantiate_model_signature
      return wrapped_import.prune(inputs, outputs)
Node: 'channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert'
2 root error(s) found.
  (0) INVALID_ARGUMENT:  assertion failed: [Fingerprint mismatch] [Condition x == y did not hold element-wise:] [x (channel_conditional/channel_block_00/decompress/Bitcast:0) = ] [-2304076079134112540] [y (channel_conditional/channel_block_00/compress/Bitcast:0) = ] [3733766143214313937]
         [[{{node channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert}}]]
         [[channel_conditional/channel_block_01/decompress/decompress/TensorArrayUnstack_1/range/_718]]
  (1) INVALID_ARGUMENT:  assertion failed: [Fingerprint mismatch] [Condition x == y did not hold element-wise:] [x (channel_conditional/channel_block_00/decompress/Bitcast:0) = ] [-2304076079134112540] [y (channel_conditional/channel_block_00/compress/Bitcast:0) = ] [3733766143214313937]
         [[{{node channel_conditional/channel_block_00/decompress/assert_equal_1/Assert/AssertGuard/Assert}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_pruned_7660]
```

Interestingly, when I disable GPU (by `CUDA_VISIBLE_DEVICES=''`), both compression and decompression can be run successfully.

**To Reproduce**
I encountered this error on my Linux machine, but a very similar error can also be reproduced on Colab:
1. Go to this Colab notebook: https://colab.research.google.com/drive/1VXLLnjoyrQ7Uq6F-ayip0pEzuqH0sjH1?usp=sharing
2. In "Runtime - Change runtime type", enable GPU
3. Run all the cells

**Expected behavior**
No error should occur.

**System (please complete the following information):**
 - Ubuntu 20.04.4 LTS, linux kernel = `5.13.0-52-generic`
 - Python 3.10.4. Installed by Conda.
 - TensorFlow version `2.9.0`, installed by `pip`
 - tensorflow-compression `2.9.1`
Perhaps the error is unrelated to the system since it can also be reproduced on Colab?

**Additional context**
This error occurs consistently when I use different images and `ms2020-cc10-mse` models.
I didn't try other models though.

**Comment by jonycgn** [comment]
Hi, this model hasn't been modified to use integer networks to compute the entropy models. So, this is a known limitation. See the output of `python tfci.py models`:

```
Note: all the models using hierarchical/hyperpriors published above include a
modification from:
J. Ballé, N. Johnston, D. Minnen:
"Integer Networks for Data Compression with Latent-Variable Models"
Int. Conf. on Learning Representations (ICLR), 2019

The conditional priors are modified to use integer arithmetic, in order to
ensure consistent results across different hardware platforms. Other than this,
the models are reproductions of the original models used in the publication.
Therefore, performance may differ slightly.
```

and, specifically for the `ms2020` models:
```
  Note: this model does not use the integer modification described below, so it
  may be necessary to disable the GPU in order to reliably encode and decode.
  This can be done by setting the environment variable `CUDA_VISIBLE_DEVICES`
  to the empty string, e.g., using the command line:
  CUDA_VISIBLE_DEVICES='' python tfci.py ...
```
