### ISSUE TITLE
KeyError: 'UnboundedIndexRangeEncode'  while loading metagraph file.

### ISSUE THREAD

**Issue by zzktb** [tensorflow/compression#32]
I want to use the pretrained model and do a fine-tuning on my dataset. But this error happens while I'm trying to load the **.metagraph** file. Am I doing it in a wrong way since I didn't find sufficient references on Google on loading a **.metagraph** file. Most are about **.meta** file.

This is the error information:
```
/home/zzktb/.virtualenvs/tf1.14_py3/bin/python /home/zzktb/PycharmProjects/End2EndVideoCompression/tfoptflow/intra/intra.py
2019-08-14 15:10:50.004926: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-14 15:10:50.008137: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.008704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
2019-08-14 15:10:50.008798: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-14 15:10:50.009523: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-14 15:10:50.010185: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-14 15:10:50.010338: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-14 15:10:50.011303: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-14 15:10:50.012014: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-14 15:10:50.014199: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-14 15:10:50.014270: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.014877: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.015432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-14 15:10:50.015655: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-14 15:10:50.089384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.090085: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x53433c0 executing computations on platform CUDA. Devices:
2019-08-14 15:10:50.090099: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-14 15:10:50.115681: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-08-14 15:10:50.116478: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x540f790 executing computations on platform Host. Devices:
2019-08-14 15:10:50.116496: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-14 15:10:50.116636: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.117236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
2019-08-14 15:10:50.117261: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-14 15:10:50.117270: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-14 15:10:50.117277: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-14 15:10:50.117284: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-14 15:10:50.117292: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-14 15:10:50.117299: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-14 15:10:50.117306: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-14 15:10:50.117338: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.117918: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.118472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-14 15:10:50.118490: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-14 15:10:50.119416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-14 15:10:50.119425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-14 15:10:50.119428: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-14 15:10:50.119602: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.120196: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-14 15:10:50.120782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9245 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "/home/zzktb/PycharmProjects/End2EndVideoCompression/tfoptflow/intra/intra.py", line 32, in <module>
    saver = tf.compat.v1.train.import_meta_graph(meta_path)
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/zzktb/.virtualenvs/tf1.14_py3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 160, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'UnboundedIndexRangeEncode'

Process finished with exit code 1
```

Here's the snippet that I'm using which is based on tensorflow docs
[https://www.tensorflow.org/api_docs/python/tf/train/import_meta_graph](url)
```
import tensorflow as tf
if __name__ == '__main__':
    meta_path = '/home/zzktb/Downloads/bmshj2018-hyperprior-msssim-8.metagraph'

    with tf.compat.v1.Session() as sess:
        saver = tf.compat.v1.train.import_meta_graph(meta_path)
        saver.restore(sess, meta_path.split('.')[0])

        print('Loaded.')
```
Since this is not working, I tried another way as in tfci.py file as follows:
```
import tensorflow as tf


def load_metagraph(file):
    """
    Load metagraph file.
    :param file:
    :return: MetaGraphDef protocol buffer
    """
    with tf.io.gfile.GFile(file, 'rb') as f:
        string = f.read()

    meta_graph = tf.MetaGraphDef()
    meta_graph.ParseFromString(string)
    tf.train.import_meta_graph(meta_graph)
    return meta_graph


if __name__ == '__main__':
    meta_path = '/home/zzktb/Downloads/bmshj2018-hyperprior-msssim-8.metagraph'

    with tf.Graph().as_default():
        meta_graph = load_metagraph(meta_path)

        print('Loaded.')
```
And the same error information happens when executing `tf.train.import_meta_graph(meta_graph)`. So anyone can enlighten me on how to correctly restore this MetaGraph and do a fine-tuning. I need the pre-trained variables.

**Comment by ssjhv** [comment]
Hi,

Did you try to import tfc in addition to tf? These custom ops should be loaded before importing the graph. Importing tfc should register these custom ops to TF runtime.

**Comment by jonycgn** [comment]
Hi zzktb, is this still an issue? Have you tried ssjhv's suggestion?

**Comment by jonycgn** [comment]
I’m closing this due to lack of response. Feel free to reopen if the issue is still there.
