### ISSUE TITLE
libtensorflow_compression.so: cannot open shared object file

### ISSUE THREAD

**Issue by moha23** [tensorflow/compression#55]
**Describe the bug**
When importing the library, it looks for libtensorflow_compression.so in cc folder but this does not exist in the master version and hence throws the error.

**To Reproduce**
1. Install tf2.1,tfp0.9.0 and tfc master version
2. import tensorflow_compression as tfc
3. Error:

 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/compression-master/tensorflow_compression/__init__.py", line 30, in <module>
    from tensorflow_compression.python.entropy_models.continuous_batched import *
  File "/home/work/compression-master/tensorflow_compression/python/entropy_models/continuous_batched.py", line 22, in <module>
    from tensorflow_compression.python.entropy_models import continuous_base
  File "/home/work/compression-master/tensorflow_compression/python/entropy_models/continuous_base.py", line 24, in <module>
    from tensorflow_compression.python.ops import range_coding_ops
  File "/home/work/compression-master/tensorflow_compression/python/ops/range_coding_ops.py", line 28, in <module>
    "../../cc/libtensorflow_compression.so")))
  File "/home/virtualenvs/tfcomp/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/work/compression-master/tensorflow_compression/python/ops/../../cc/libtensorflow_compression.so: cannot open shared object file: No such file or directory

**Expected behavior**
Should be able to import without issues

**System (please complete the following information):**
 - OS Ubuntu20.04
 - Python version 3.6.9, built from source
 - TensorFlow version 2.1.2, pip
 - tensorflow-compression version master

I need a tf2 compatible version tfc hence trying to use the master version

**Comment by moha23** [comment]
The `build_pip_pkg.py` file has option to build a pip package, but will doing that also create this file? It seems `bazel run` should create this file? I tried running `bazel run -c opt --copt=-mavx :build_pip_pkg` within a virtual environment having tf2.1.2, but it fails with following errors:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:build_pip_pkg (25 packages loaded, 2541 targets configured).
INFO: Found 1 target...
ERROR: /home/m/.cache/bazel/_bazel_m/eea04f7db7c60e6c8a1899b84b76b3dd/external/tensorflow_pip/BUILD:2:11: @tensorflow_pip//:libtensorflow_framework: missing input file 'external/tensorflow_pip/libtensorflow_framework.so.1', owner: '@tensorflow_pip//:libtensorflow_framework.so.1'
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/m/.cache/bazel/_bazel_m/eea04f7db7c60e6c8a1899b84b76b3dd/external/tensorflow_pip/BUILD:2:11 1 input file(s) do not exist
INFO: Elapsed time: 38.482s, Critical Path: 0.42s
INFO: 12 processes: 12 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

The docker process seems necessary (?), i'm just not sure about which tensorflow image etc to use, but will try the same instructions (except change tf1.15 to tf2.1.2) in README and update.

**Comment by moha23** [comment]
I tried building the pip package as follows:

sudo docker run -v /tmp/tensorflow_compression:/tmp/tensorflow_compression  /
   tensorflow/tensorflow:custom-op-ubuntu16 bash -c   /
  "pip3 install --proxy=http://proxyaddr:port tensorflow==2.1.2 && 
pip3 install --proxy=http://proxyaddr:port tensorflow-probability==0.9.0 && 
mkdir /tensorflow_compression && 
git config --global http.proxy http://proxyaddr:port && 
git clone https://github.com/tensorflow/compression.git /tensorflow_compression &&
     cd /tensorflow_compression && 
export HTTPS_PROXY=http://proxyaddr:port && 
export HTTP_PROXY=http://proxyaddr:port &&
     bazel run -c opt --copt=-mavx :build_pip_pkg"


I get the following error:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Analyzing: target //:build_pip_pkg (1 packages loaded, 0 targets configured)
Analyzing: target //:build_pip_pkg (6 packages loaded, 7 targets configured)
Analyzing: target //:build_pip_pkg (17 packages loaded, 18 targets configured)
INFO: Call stack for the definition of repository 'tensorflow_pip' which is a tensorflow_pip (rule definition at /tensorflow_compression/workspace.bzl:42:18):
 - /tensorflow_compression/workspace.bzl:50:3
 - /tensorflow_compression/WORKSPACE:4:1
ERROR: An error occurred during the fetch of repository 'tensorflow_pip':
   Failed to find library path. Did you remember to pip install tensorflow?: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
ERROR: /tensorflow_compression/tensorflow_compression/cc/BUILD:3:1: //tensorflow_compression/cc:libtensorflow_compression.so depends on @tensorflow_pip//:libtensorflow_framework in repository @tensorflow_pip which failed to fetch. no such package '**@tensorflow_pip//': Failed to find library path. Did you remember to pip install tensorflow?:** Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
ERROR: Analysis of target '//:build_pip_pkg' failed; build aborted: no such package '@tensorflow_pip//': Failed to find library path. Did you remember to pip install tensorflow?: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorflow
INFO: Elapsed time: 29.918s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (22 packages loaded, 141 targets configured)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (22 packages loaded, 141 targets configured)

How can i fix this?

**Comment by moha23** [comment]
Previous error gets fixed by changing 'python' to 'python3' in the .bzl file, the error now is:

INFO: Analyzed target //:build_pip_pkg (3 packages loaded, 2411 targets configured).
INFO: Found 1 target...
ERROR: missing input file '@tensorflow_pip//:libtensorflow_framework.so.1'
ERROR: /root/.cache/bazel/_bazel_root/d5a5ee1fe6882ba2eee00312cabba7ca/external/tensorflow_pip/BUILD:2:1: @tensorflow_pip//:libtensorflow_framework: missing input file '@tensorflow_pip//:libtensorflow_framework.so.1'
Target //:build_pip_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /root/.cache/bazel/_bazel_root/d5a5ee1fe6882ba2eee00312cabba7ca/external/tensorflow_pip/BUILD:2:1 1 input file(s) do not exist
INFO: Elapsed time: 8.484s, Critical Path: 0.01s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully


I tried going to '/usr/local/lib/python3.6/dist-packages' within the container and created a symlink using `ln -s libtensorflow_framework.so.2 libtensorflow_framework.so.1` since file libtensorflow_framework.so.2 exists there but still get the same error. Is it possible I am using the wrong docker image?

**Comment by moha23** [comment]
ok this error goes away on changing `libtensorflow_framework.so.1` to `libtensorflow_framework.so.2` in the `.bzl` file. Thanks to the patch provided by @trougnouf The wheel builds without error and i'm able to import the library without error too. Although `python -m tensorflow_compression.python.all_test` doesn't seem to have been successful, will open new issue if I face other errors, I'm not very sure if my build process was fine. :)

**Comment by jonycgn** [comment]
Hi, thanks for reporting this and figuring these things out. See my reply in the Google group - we hope to get the new API in a stable form soon, and planning to make a new release by the end of the year. I will bookmark this bug and take this into account when looking into building new pip packages :)

**Comment by moha23** [comment]
Hi @jonycgn, sorry to bug, just wondering when the release will happen? Trying to build it for Tf2 now throws some new errors because the repo has had changes since. Thanks again!

**Comment by jonycgn** [comment]
Hi, our schedules are still quite tight, but I will make an effort to make a beta release against the latest TF2 release in the next couple of days. We can't really make a full release yet, because parts of the library haven't been ported yet, and the API is still seeing changes.

**Comment by moha23** [comment]
A beta release will be very helpful.
